# 先に読み込んでほしいプラグインを羅列するファイル

# すべての始まり。dein
[[plugins]]
repo = 'Shougo/dein.vim'

# カラースキーマ molokaiのインスコ
[[plugins]]
repo = 'tomasr/molokai'
# hook_add = '''
#   au MyAutoCmd VimEnter * nested colorscheme molokai
# '''

# いろいろ動かすのに必要になる vimproc
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
